spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: local_user
    password: local_password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    com.example.demo: DEBUG
    org.springframework.batch: DEBUG
    org.mybatis: DEBUG
  file:
    name: logs/batch-local.log
    max-size: 10MB
    max-history: 30
