spring:
  # H2 Database Configuration (메타데이터 저장용)
  # Spring Batch는 Job 실행 이력을 데이터베이스에 저장합니다
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:batchdb
    username: sa
    password:

  # H2 Console 활성화 (개발 중 배치 메타데이터 확인용)
  h2:
    console:
      enabled: true

  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    com.example.demo: DEBUG
    org.springframework.batch: DEBUG
    org.mybatis: DEBUG
  file:
    name: logs/batch-local.log
    max-size: 10MB
    max-history: 30
