spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@prd2-db-server:1521:PRD2DB
    username: prd2_user
    password: prd2_password
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20

  batch:
    jdbc:
      initialize-schema: never

logging:
  level:
    com.example.demo: INFO
    org.springframework.batch: WARN
    org.mybatis: WARN
  file:
    name: logs/batch-prd2.log
    max-size: 200MB
    max-history: 90
